require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AlianzasController do

  # This should return the minimal set of attributes required to create a valid
  # Alianza. As you add validations to Alianza, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nombre" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AlianzasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all alianzas as @alianzas" do
      alianza = Alianza.create! valid_attributes
      get :index, {}, valid_session
      assigns(:alianzas).should eq([alianza])
    end
  end

  describe "GET show" do
    it "assigns the requested alianza as @alianza" do
      alianza = Alianza.create! valid_attributes
      get :show, {:id => alianza.to_param}, valid_session
      assigns(:alianza).should eq(alianza)
    end
  end

  describe "GET new" do
    it "assigns a new alianza as @alianza" do
      get :new, {}, valid_session
      assigns(:alianza).should be_a_new(Alianza)
    end
  end

  describe "GET edit" do
    it "assigns the requested alianza as @alianza" do
      alianza = Alianza.create! valid_attributes
      get :edit, {:id => alianza.to_param}, valid_session
      assigns(:alianza).should eq(alianza)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Alianza" do
        expect {
          post :create, {:alianza => valid_attributes}, valid_session
        }.to change(Alianza, :count).by(1)
      end

      it "assigns a newly created alianza as @alianza" do
        post :create, {:alianza => valid_attributes}, valid_session
        assigns(:alianza).should be_a(Alianza)
        assigns(:alianza).should be_persisted
      end

      it "redirects to the created alianza" do
        post :create, {:alianza => valid_attributes}, valid_session
        response.should redirect_to(Alianza.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved alianza as @alianza" do
        # Trigger the behavior that occurs when invalid params are submitted
        Alianza.any_instance.stub(:save).and_return(false)
        post :create, {:alianza => { "nombre" => "invalid value" }}, valid_session
        assigns(:alianza).should be_a_new(Alianza)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Alianza.any_instance.stub(:save).and_return(false)
        post :create, {:alianza => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested alianza" do
        alianza = Alianza.create! valid_attributes
        # Assuming there are no other alianzas in the database, this
        # specifies that the Alianza created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Alianza.any_instance.should_receive(:update_attributes).with({ "nombre" => "MyString" })
        put :update, {:id => alianza.to_param, :alianza => { "nombre" => "MyString" }}, valid_session
      end

      it "assigns the requested alianza as @alianza" do
        alianza = Alianza.create! valid_attributes
        put :update, {:id => alianza.to_param, :alianza => valid_attributes}, valid_session
        assigns(:alianza).should eq(alianza)
      end

      it "redirects to the alianza" do
        alianza = Alianza.create! valid_attributes
        put :update, {:id => alianza.to_param, :alianza => valid_attributes}, valid_session
        response.should redirect_to(alianza)
      end
    end

    describe "with invalid params" do
      it "assigns the alianza as @alianza" do
        alianza = Alianza.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Alianza.any_instance.stub(:save).and_return(false)
        put :update, {:id => alianza.to_param, :alianza => { "nombre" => "invalid value" }}, valid_session
        assigns(:alianza).should eq(alianza)
      end

      it "re-renders the 'edit' template" do
        alianza = Alianza.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Alianza.any_instance.stub(:save).and_return(false)
        put :update, {:id => alianza.to_param, :alianza => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested alianza" do
      alianza = Alianza.create! valid_attributes
      expect {
        delete :destroy, {:id => alianza.to_param}, valid_session
      }.to change(Alianza, :count).by(-1)
    end

    it "redirects to the alianzas list" do
      alianza = Alianza.create! valid_attributes
      delete :destroy, {:id => alianza.to_param}, valid_session
      response.should redirect_to(alianzas_url)
    end
  end

end
